### ISSUE TITLE
제가 좋아하는 술들을 전달해보아요

### ISSUE THREAD

**Issue by koremp** [dmydms/tastes#1]
## 스카치 싱글몰트 위스키

* 달휘니 15y - 과일향
* 맥캘란 - 맛남

## 피트

* 라가불린 16y - 피트
* 라프로익 10y - 피트

## 기타 싱글몰트 위스키

* 카발란

## 버번 위스키

* 와일드 터키 101 8y

진

* 몽키 47 - 글라스로 마셔도 좋은 진

럼

* 돈파파

**Comment by koremp** [comment]
클레어가

**Comment by dmydms** [comment]
@koremp 추가했어요 >,< ([커밋보기](https://github.com/dmydms/tastes/commit/35f0a0041cf7a96a0aea1e828eb4a695342a832a))

**Comment by dmydms** [comment]
고맙습니다 >,,<
